function bootstrap {
  [CmdletBinding(DefaultParametersetName = 'skip')]
  param (
    [Parameter(ParameterSetName = "skip")]
    [switch]
    $update,

    [Parameter(ParameterSetName = "skip")]
    [switch]
    $skip,

    [Parameter(ParameterSetName = "skip")]
    [switch]
    $linux
  )
  # OK this file partially is dynamically generated by ../scripts/bootstrap.ps1
  # BUILD_START
}
