name: windows/lint

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'windows/**/*.ps1'
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: windows

jobs:
  lint:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@v1.0
      with:
        path: .\
        recurse: true 
        output: results.sarif
    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif